package jclasschin.entity;
// Generated Jun 19, 2014 7:07:55 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Classroom generated by hbm2java
 */
public class Classroom  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String floor;
     private Integer capacity;
     private Boolean dataProjector;
     private Boolean blackboard;
     private Boolean whiteboard;
     private String description;
     private Set dedications = new HashSet(0);

    public Classroom() {
    }

	
    public Classroom(String name) {
        this.name = name;
    }
    public Classroom(String name, String floor, Integer capacity, Boolean dataProjector, Boolean blackboard, Boolean whiteboard, String description, Set dedications) {
       this.name = name;
       this.floor = floor;
       this.capacity = capacity;
       this.dataProjector = dataProjector;
       this.blackboard = blackboard;
       this.whiteboard = whiteboard;
       this.description = description;
       this.dedications = dedications;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getFloor() {
        return this.floor;
    }
    
    public void setFloor(String floor) {
        this.floor = floor;
    }
    public Integer getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(Integer capacity) {
        this.capacity = capacity;
    }
    public Boolean getDataProjector() {
        return this.dataProjector;
    }
    
    public void setDataProjector(Boolean dataProjector) {
        this.dataProjector = dataProjector;
    }
    public Boolean getBlackboard() {
        return this.blackboard;
    }
    
    public void setBlackboard(Boolean blackboard) {
        this.blackboard = blackboard;
    }
    public Boolean getWhiteboard() {
        return this.whiteboard;
    }
    
    public void setWhiteboard(Boolean whiteboard) {
        this.whiteboard = whiteboard;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getDedications() {
        return this.dedications;
    }
    
    public void setDedications(Set dedications) {
        this.dedications = dedications;
    }




}


