package jclasschin.entity;
// Generated Jun 19, 2014 7:07:55 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course  implements java.io.Serializable {


     private Integer id;
     private Coursetype coursetype;
     private Field field;
     private String name;
     private Set cctms = new HashSet(0);

    public Course() {
    }

	
    public Course(String name) {
        this.name = name;
    }
    public Course(Coursetype coursetype, Field field, String name, Set cctms) {
       this.coursetype = coursetype;
       this.field = field;
       this.name = name;
       this.cctms = cctms;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Coursetype getCoursetype() {
        return this.coursetype;
    }
    
    public void setCoursetype(Coursetype coursetype) {
        this.coursetype = coursetype;
    }
    public Field getField() {
        return this.field;
    }
    
    public void setField(Field field) {
        this.field = field;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getCctms() {
        return this.cctms;
    }
    
    public void setCctms(Set cctms) {
        this.cctms = cctms;
    }




}


