package jclasschin.entity;
// Generated Jun 19, 2014 7:07:55 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Coursetype generated by hbm2java
 */
public class Coursetype  implements java.io.Serializable {


     private Integer id;
     private String type;
     private Set courses = new HashSet(0);

    public Coursetype() {
    }

	
    public Coursetype(String type) {
        this.type = type;
    }
    public Coursetype(String type, Set courses) {
       this.type = type;
       this.courses = courses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }




}


