package jclasschin.entity;
// Generated Jun 20, 2014 4:27:44 PM by Hibernate Tools 3.6.0



/**
 * Ctacss generated by hbm2java
 */
public class Ctacss  implements java.io.Serializable {


     private Integer id;
     private Schedule schedule;
     private Term term;

    public Ctacss() {
    }

    public Ctacss(Schedule schedule, Term term) {
       this.schedule = schedule;
       this.term = term;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Schedule getSchedule() {
        return this.schedule;
    }
    
    public void setSchedule(Schedule schedule) {
        this.schedule = schedule;
    }
    public Term getTerm() {
        return this.term;
    }
    
    public void setTerm(Term term) {
        this.term = term;
    }




}


