package jclasschin.entity;
// Generated May 13, 2014 4:54:01 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Field generated by hbm2java
 */
public class Field  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set statuses = new HashSet(0);
     private Set persons = new HashSet(0);
     private Set dedications = new HashSet(0);
     private Set courses = new HashSet(0);

    public Field() {
    }

	
    public Field(String name) {
        this.name = name;
    }
    public Field(String name, Set statuses, Set persons, Set dedications, Set courses) {
       this.name = name;
       this.statuses = statuses;
       this.persons = persons;
       this.dedications = dedications;
       this.courses = courses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getStatuses() {
        return this.statuses;
    }
    
    public void setStatuses(Set statuses) {
        this.statuses = statuses;
    }
    public Set getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set persons) {
        this.persons = persons;
    }
    public Set getDedications() {
        return this.dedications;
    }
    
    public void setDedications(Set dedications) {
        this.dedications = dedications;
    }
    public Set getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set courses) {
        this.courses = courses;
    }




}


