package jclasschin.entity;
// Generated Jun 19, 2014 7:07:55 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Job generated by hbm2java
 */
public class Job  implements java.io.Serializable {


     private Integer id;
     private String title;
     private Set persons = new HashSet(0);

    public Job() {
    }

	
    public Job(String title) {
        this.title = title;
    }
    public Job(String title, Set persons) {
       this.title = title;
       this.persons = persons;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Set getPersons() {
        return this.persons;
    }
    
    public void setPersons(Set persons) {
        this.persons = persons;
    }




}


