package jclasschin.entity;
// Generated Jun 20, 2014 4:27:44 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Period generated by hbm2java
 */
public class Period  implements java.io.Serializable {


     private Integer id;
     private Schedule schedule;
     private Date start;
     private Date end;
     private Set cctms = new HashSet(0);

    public Period() {
    }

    public Period(Schedule schedule, Date start, Date end, Set cctms) {
       this.schedule = schedule;
       this.start = start;
       this.end = end;
       this.cctms = cctms;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Schedule getSchedule() {
        return this.schedule;
    }
    
    public void setSchedule(Schedule schedule) {
        this.schedule = schedule;
    }
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }
    public Date getEnd() {
        return this.end;
    }
    
    public void setEnd(Date end) {
        this.end = end;
    }
    public Set getCctms() {
        return this.cctms;
    }
    
    public void setCctms(Set cctms) {
        this.cctms = cctms;
    }




}


