package jclasschin.entity;
// Generated May 13, 2014 4:54:01 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Status generated by hbm2java
 */
public class Status  implements java.io.Serializable {


     private Integer id;
     private Term term;
     private Field field;
     private Date lastUpdate;
     private Boolean state;

    public Status() {
    }

	
    public Status(Field field) {
        this.field = field;
    }
    public Status(Term term, Field field, Date lastUpdate, Boolean state) {
       this.term = term;
       this.field = field;
       this.lastUpdate = lastUpdate;
       this.state = state;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Term getTerm() {
        return this.term;
    }
    
    public void setTerm(Term term) {
        this.term = term;
    }
    public Field getField() {
        return this.field;
    }
    
    public void setField(Field field) {
        this.field = field;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }




}


