package jclasschin.entity;
// Generated Jun 19, 2014 7:07:55 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Term generated by hbm2java
 */
public class Term  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set mails = new HashSet(0);
     private Set dedications = new HashSet(0);
     private Set statuses = new HashSet(0);

    public Term() {
    }

	
    public Term(String name) {
        this.name = name;
    }
    public Term(String name, Set mails, Set dedications, Set statuses) {
       this.name = name;
       this.mails = mails;
       this.dedications = dedications;
       this.statuses = statuses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getMails() {
        return this.mails;
    }
    
    public void setMails(Set mails) {
        this.mails = mails;
    }
    public Set getDedications() {
        return this.dedications;
    }
    
    public void setDedications(Set dedications) {
        this.dedications = dedications;
    }
    public Set getStatuses() {
        return this.statuses;
    }
    
    public void setStatuses(Set statuses) {
        this.statuses = statuses;
    }




}


