package jclasschin.entity;
// Generated Jun 19, 2014 7:07:55 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Weekday generated by hbm2java
 */
public class Weekday  implements java.io.Serializable {


     private Integer id;
     private String dayName;
     private Set cctms = new HashSet(0);

    public Weekday() {
    }

	
    public Weekday(String dayName) {
        this.dayName = dayName;
    }
    public Weekday(String dayName, Set cctms) {
       this.dayName = dayName;
       this.cctms = cctms;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDayName() {
        return this.dayName;
    }
    
    public void setDayName(String dayName) {
        this.dayName = dayName;
    }
    public Set getCctms() {
        return this.cctms;
    }
    
    public void setCctms(Set cctms) {
        this.cctms = cctms;
    }




}


